apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "DevCheckOps2"

  links:
    - url: https://github.com/RohanAwasthi/DevOpsRepo2
      title: "DevCheckOps2"
      icon: code

  labels:
    system: web-apps
    environmentname: devops1-env

  tags:
    - python
    - aws
    - "applicationtype-webapplication"

  annotations:
    # add elastic beanstalk annotation
    jenkins.io/github-folder: 'custom-actions/tf-DevCheckOps2'
    github.com/project-slug: RohanAwasthi/DevOpsRepo2
    dev.azure.com/project: 'https://dev.azure.com/EYFSDigitalEngineering/SDAFY24'
    dev.azure.com/build-definition: 'https://dev.azure.com/EYFSDigitalEngineering/SDAFY24/_build?definitionId=989'
    backstage.io/techdocs-ref: dir:.
    backstage.io/linguist: https://github.com/ItRachii/ebs-sample-python-application
    sonarqube.org/project-key: 'python-app/aws-elb-python'

spec:
  type: service
  lifecycle: experimental
  system: elasticbeanstalk
  owner: "Developers"
